[meta]
version = 1
name = "Black"
description = "A theme for the black nixos config"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent = "#24c8c8c8"
accent_foreground = "#2f6fed"
background = "#000000"
foreground = "#c8c8c8"
secondary_background = "#000000"
border = "#c8c8c8"

[colors.input]
border = "#24c8c8c8"
border_focus = "#24c8c8c8"
border_error = "#b9543b"

[colors.button.primary]
background = "#24c8c8c8"
foreground = "#e8e6e1"

[colors.list.item.selection]
background = "#bf2d2d2d"

